### ISSUE TITLE
SFML port available

### ISSUE THREAD

**Issue by deniskropp** [anvaka/atree#16]
Hey there,

thanks for the nice example. Please add a link to my SFML port over here:

https://github.com/deniskropp/christmas_tree

Cheers!

**Comment by anvaka** [comment]
Done: https://github.com/anvaka/atree/commit/254a77582cc7ee58ebaa213ab7e466ee269e5b2c

Thank you

**Comment by Korfung** [comment]
你的邮件已收到!多谢

**Comment by Korfung** [comment]
你的邮件已收到!多谢
